default_language_version:
    python: python3.8
fail_fast: false
# exclude: \.(ipynb)$
default_stages: [commit]
repos:
-   repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args:
        -   '--maxkb=10000'
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args:
        -   '--no-sort-keys'
-   repo: 'https://github.com/psf/black'
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: 'https://github.com/pycqa/flake8'
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args:
        - '--application-directories=.:src:tests'
-   repo: local
    hooks:
    -   id: pytest
        name: run-base-tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
